### ISSUE TITLE
Pydoc should be included in  $VIRTUAL_ENV/bin

### ISSUE THREAD

**Issue by cmcginty** [pyenv/pyenv-virtualenv#197]
`pydoc` is missing from `$VIRTUAL_ENV/bin` but this is a default binary provided by the python install.

There was a similar issue reported in [virtualenv](https://github.com/pypa/virtualenv/issues/149).

**Comment by jmgurney** [comment]
I agree, the alias solution is less than ideal.

Since it is not an executable in $VIRTUAL_ENV/bin, but an alias, it does not survive subshell execution, while other features of the environment do survive, and python -m pydoc xxx works in the subshell.

**Comment by blueyed** [comment]
By now it seems to be a shell function (https://github.com/pypa/virtualenv/issues/149#issuecomment-174166819), which also won't be used in subshells.
I think it needs to be fixed in virtualenv really (which is the issue above).
As a workaround adding some wrapper like the following in your `~/bin` as `pydoc` might help:
```sh
#!/bin/sh
python -m pydoc "$@"
```

**Comment by rsd** [comment]
Just for reference, this works very well:

`alias pydoc="python -m pydoc"`
[https://notoriousno.blogspot.com/2016/09/python-alias-commands-that-play-nice.html](url)
