### ISSUE TITLE
Bash user report: error about PROMPT_COMMAND with _pyenv_virtualenv_hook

### ISSUE THREAD

**Issue by openalmeida** [pyenv/pyenv-virtualenv#247]
Hi,

```1st``` Pyenv is a great tool, thanks a lot and i feedback here hope this is not a disturbing.

I've build a configure file ```/etc/profile.d/pyenv.sh``` with content below
```
eval "$(pyenv init - 2>/dev/null)" 2>/dev/null
eval "$(pyenv virtualenv-init - 2>/dev/null)" 2>/dev/null
```
because Archlinux package tool `yaourt`
install it to global path prefix (/usr/bin) for all users, but i got error below when i re-login

```Bash
-bash: PROMPT_COMMAND: line 1: syntax error near unexpected token `;;'
-bash: PROMPT_COMMAND: line 1: `_pyenv_virtualenv_hook;; printf "\033]0;%s@%s:%s\007" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/\~}"'
```
it is under Bash Version 4.4.12(1) at Archlinux-2018.01.01-x86_64,
i am a newbie for Bash programming, but i submit my patched below:
```Patch
pyenv-virtualenv-init::143

- PROMPT_COMMAND="_pyenv_virtualenv_hook;\$PROMPT_COMMAND";
+ PROMPT_COMMAND="_pyenv_virtualenv_hook \$PROMPT_COMMAND"
```
at least it works for me.

```2ed```, maybe script below will help a little if someone want PATH auto-hook via Aur's PKGBUILD like me when pyenv installing.

```Bash
sudo tee > /dev/null <<EOF /etc/profile.d/pyenv.sh
#!/bin/bash
if [ -z "\$(which pyenv 2>/dev/null)" -a -x "\$HOME/.pyenv/bin/pyenv" ]; then
    export PATH=\$HOME/.pyenv/bin:\$PATH
fi
if [ -x "\$(which pyenv 2>/dev/null)" ]; then
       eval "\$(pyenv init - 2>/dev/null)" 2>/dev/null \\
    && eval "\$(pyenv virtualenv-init - 2>/dev/null)" 2>/dev/null
    if [ ! 0 = \$? ]; then
        echo "[*] pyenv PATH hook error, trigger: '/etc/profile.d/pyenv.sh'."
    fi
else
    echo "[*] pyenv may not exists, plz handle '/etc/profile.d/pyenv.sh'"
fi
EOF
```

P.S For Aur or any package installing, how about set a switch (or an alt-package, ```e.g``` pyenv-full-auto-hook) about PATH hook automate or not ?

**Comment by rjmorris** [comment]
I ran across this error message, too, but I don't think the patch provided here is the correct solution. The suggestion was to remove the semicolon after `_pyenv_virtualenv_hook`, but that will break setups that have a well-formed prior value for `PROMPT_COMMAND`.

I think the pyenv code is doing the right thing here (with the exception of failing to check whether `PROMPT_COMMAND` is empty, as reported in #269). Instead, I think the problem that the OP ran into, and the one I ran into, was caused by our prior value of `PROMPT_COMMAND` beginning with a semicolon. In the OP's case, the prior value was:

```
; printf "\033]0;%s@%s:%s\007" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/\~}"
```

If you try to use that _without even installing or initializing pyenv_, you will get a similar error:

```
bash: PROMPT_COMMAND: line 0: syntax error near unexpected token `;'
bash: PROMPT_COMMAND: line 0: `; printf "\033]0;%s@%s:%s\007" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/\~}"'
```

For me, the solution was to fix my `~/.bashrc` so that my `PROMPT_COMMAND` didn't start with a semicolon in the first place.
