### ISSUE TITLE
install virtualenv in project directory

### ISSUE THREAD

**Issue by marcosfede** [pyenv/pyenv-virtualenv#408]
Hi, I wonder if its possible to install the virtualenv on the projects directory instead of installing it in .pyenv/versions .
there are many tools that assume you have your venvs on the same directory like vscode. 

Is there any flag I can add to `pyenv virtualenv` to do this?

**Comment by tvalentyn** [comment]
Does anyone see any concern with a following solution to the question raised OP:

```
pyenv install -s 3.8.3 # install preferred version if needed
PYENV_VERSION=3.8.3 python -m venv /tmp/your/prefered/dir ; source /tmp/your/prefered/dir/activate
```

Instead of creating an environment with `pyenv virtualenv`, we are using the interpreter provided by pyenv, but create an environment in a desired location ourselves via `python -m venv`.

**Comment by native-api** [comment]
2all:

What are the use cases where you need this?

---

The only one use case given so far is in CI where you need to clean up envs between bulids -- this can be achieved with `pyenv virtualenvs --bare --skip-aliases | xargs -n 1 pyenv virtualenv-delete -f`

---

There has also been a request to use a different base directory for Pyenv-Virtualenv than `$(pyenv root)` if Pyenv is installed globally -- it may be useful for this case, too.

**Comment by tvalentyn** [comment]
> What are the use cases where you need this?
Somewhat orthogonal, but in one use case, I need a developer environment to have one Python interpreter per Python minor version, and I would prefer to make as little assumptions about how interpreters are provided: via apt, compiled from sources, or via pyenv. I would personally prefer pyenv, since it allows a convenient fine-grained control over python patch versions, and does interfere with system's installation of Python. I install Pythons, make several interpreters globally available via `pyenv global 3.5.6 3.6.8 3.7.10 ...`. Then, I can provide universal commands to create an environment via `python3.x -m venv /tmp/your/prefered/dir` that would work for me and other developers on the project who decided to choose a different tooling for installing pythons and/or managing environments.

> The only one use case given so far is in CI where you need to clean up envs between bulids -- this can be achieved with `pyenv virtualenvs --bare --skip-aliases | xargs -n 1 pyenv virtualenv-delete -f`

The 'between builds' part may be tricky to time if multiple builds run continuously on the same worker. 

> There has also been a request to use a different base directory for Pyenv-Virtualenv than `$(pyenv root)` if Pyenv is installed globally -- it may be useful for this case, too.

Where is this tracked?

**Comment by native-api** [comment]
@tvalentyn, thanks for the info!

If a virtualenv is located in some arbitrary place -- and can have a duplicate name, too (in case of multiple concurrent CI builds) -- how do you expect Pyenv to find/distinguish/manage it (e.g. for commands like `pyenv virtualenvs`)?

I guess the most obvious solution would be to allow to specify a path instead of env's name! (a path in the current dir will have to be prepended with `./`, I guess, to distinguish it from a plain name).
(`pyenv virtualenvs` won't be able to find it -- but that doesn't sound like something that concerns you too much.)

(Another solution would be to use a different optional envvar for Pyenv-Virtualenv's base path -- but since the base path is supposed to support multiple envs, Pyenv-Virtualenv will have to create the same kind of dir hierarchy there as it does now -- which sounds like not what you want.)

**Comment by vedal** [comment]
@yyuu  Any chance we could re-open this? I was thinking of a use-case where one could drop pyenv-virtualenv in favor of poetry (as pyenv-virtualenv updates are sporadic) and have poetry manage venvs instead. Then, one could just point pyenv to the poetry venv with `pyenv local path/to/poetry-venv`. Poetry already has support for same-folder venv through
`poetry config virtualenvs.in-project true`

**Comment by native-api** [comment]
Just use bare `virtualenv`. If you want to switch to it via Pyenv, symlink to it in `$PYENV_ROOT/versions`. There's even a 3rd-party plugin to do that.

Or conversely, create the environment with Pyenv-Virtualenv and symlink to it in your project.

---

The entire purpose of Pyenv-Virtualenv is to manage created virtual environments the same as installed Python versions. This implies that the repository of them has to be global (for a specific `PYENV_ROOT`) and not spread around project directories -- otherwise, how would we compose a full list of them to be able to select from?

**Comment by dhiegomaga** [comment]
The best solution imo is to use `pyenv` just to manage the base python versions, and then manage packages locally using `virtualenv`, to keep everything contained inside the repo. 

```bash
# Get the python base version you need
pyenv install 3.8

# Activate that python for the current terminal window
pyenv shell 3.8

# Create environment in local folder
virtualenv .venv -p $(which python)

# Activate environment
source .venv/bin/activate

# Install libraries
pip install numpy boto3 # ...etc

# Export current environment
pip freeze > requirements.txt

# Install from environment
pip install -r requirements.txt
``` 

Other solutions are to use either Anaconda (easiest imo, but can have some licensing issues), or Poetry.

**Comment by native-api** [comment]
> otherwise, how would we compose a full list of them to be able to select from?

> The best solution imo is to use `pyenv` just to manage the base python versions, and then manage packages locally using `virtualenv`, to keep everything contained inside the repo.

It should probably be possible to add an ability to Pyenv-Virtualenv to use a locally created environment.

But then you won't be able to select it from an arbitrary place (or will have to specify its full path instead of just name to do so).

**Comment by russellvt** [comment]
> The best solution imo is to use `pyenv` just to manage the base python versions, and then manage packages locally using `virtualenv`, to keep everything contained inside the repo.

This is, essentially, what I have done, myself (despite still being a command-line based UN\*X junkie); even to the point of "using VIM for an IDE" (ie. no VS here). It also/essentially means you need to maintain a development environment (ie. libraries and headers) for your operating/development environment ... and then use `pyenv` to maintain the specific Python modules (which may also require changes to your development environment).

**Comment by Milor123** [comment]
This solution was amazing for me ! https://stackoverflow.com/a/69441370/4941927
